title: HTTP Squirrel Codes
author: tddapps.com
description: >
  HTTP Status Codes with squirrels  
meta_description: >
  HTTP Status Codes with squirrel images.
  Squirrels are cute.
  They're good to explain what http status codes mean.  
keywords:
  - http
  - status
  - codes
  - squirrel
  - http status
  - status code
  - http status code squirrel
  - squirrel images
  - cute squirrel
  - dead squirrel
baseurl: ""
url: "https://s.tddapps.com"
google_analytics: UA-98488669-1

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - dev
  - Gemfile
  - Gemfile.lock
  - README.md
  - readme-dev.md
include: ['_pages']
defaults:
    -
        scope:
            path: "_pages"
            type: pages
        values:
            layout: home
